---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: breakglass-listener-interceptor
spec:
  triggers:
    - name: breakglass-listener
      interceptors:
        - cel:
            overlays:
            - key: alert-body
              expression: "body.alert.marshalJSON()"
      bindings:
        - ref: breakglass-ticket-create-binding
      template:
        ref: breakglass-ticket-check
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: breakglass-ticket-create-binding
spec:
  params:
    - name: alertId
      value: $(body.alert.id)
    - name: break-glass-annotation
      value: $(body.alert.deployment.annotations.admission\.stackrox\.io/break-glass)
    - name: alert-body
      value: $(extensions.alert-body)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: breakglass-ticket-check
spec:
  params:
    - name: alertId
    - name: break-glass-annotation
    - name: alert-body
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: breakglass-ticket-check-
      spec:
        pipelineRef:
          name: breakglass-ansible-pipeline-runner
        params:
        - name: alertId
          value: "$(tt.params.alertId)"
        - name: break-glass-annotation
          value: "$(tt.params.break-glass-annotation)"
        - name: alert-body
          value: "$(tt.params.alert-body)"
        workspaces:
        - name: files
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-breakglass-trigger
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: breakglass-listener-interceptor
spec:
  to:
    kind: Service
    name: el-breakglass-listener-interceptor
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None