- hosts: localhost
  connection: local
  tasks:
    - name: Check existence of ticket
      jira:
        uri: '{{ jira_uri }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        project: '{{ break_glass_annotation.split("-")[0] | upper }}'
        operation: fetch
        issue: '{{ break_glass_annotation }}'
      register: issue
    - name: Show issue
      debug:
        msg: "{{ issue }}"
    - name: Resolve Alert
      uri:
        url: "https://{{ acs_endpoint }}/v1/apitokens/generate"
        body: '{"id":"{{ alert_id }}","whitelist":"false","addToBaseline":"false"}'
        method: PATCH
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ acs_api_token }}"
        body_format: json
        force_basic_auth: true
        validate_certs: no
      when: 
        - issue.meta.fields.issuetype.name == "Exception"
        - issue.meta.fields.status.name == "In Progress"

         