- hosts: localhost
  connection: local
  vars:
    alert: "{{ alert_body | from_json }}"
  tasks:


    - debug: var=alert

    - debug: var=alert.deployment

    - name: Check existence of ticket
      jira:
        uri: '{{ jira_uri }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        project: '{{ alert.deployment.annotations["admission.stackrox.io/break-glass"].split("-")[0] | upper }}'
        operation: fetch
        issue: '{{ alert.deployment.annotations["admission.stackrox.io/break-glass"] }}'
      register: issue
      # It's OK if we get an error if ticket doesn't exist.
      ignore_errors: yes

    - set_fact: 
        ticket_valid: "false"
# default state unless the ticket is actually valid

    - name: Set fact if ticket is valid
      set_fact: 
        ticket_valid: "true"
      when: 
        - ((issue.meta.fields.issuetype.name is defined) and (issue.meta.fields.issuetype.name == "Exception"))
        - ((issue.meta.fields.status.name is defined) and (issue.meta.fields.status.name == "In Progress"))

    - debug: var=ticket_valid

    - name: Add comment to ticket
      jira:
        uri: '{{ jira_uri }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        project: '{{ alert.deployment.annotations["admission.stackrox.io/break-glass"].split("-")[0] | upper }}'
        operation: comment
        comment: "Exception used by {{ alert.deployment.namespace }}/{{ alert.deployment.name }} at {{ now() }}"
        issue: '{{ alert.deployment.annotations["admission.stackrox.io/break-glass"]}}'
      when: ticket_valid == true

    - name: Scale down unauthorized deployment
      k8s_scale:
        api_version: v1
        kind: '{{ alert.deployment.type }}'
        namespace: '{{ alert.deployment.namespace }}'
        name: '{{ alert.deployment.name }}'
        replicas: 0
      when: ticket_valid == false
        
    - name: Create an issue for unauthorized deployment
      jira:
        uri: '{{ server }}'
        username: '{{ user }}'
        password: '{{ pass }}'
        project: SEC
        operation: create
        summary: Unauthorized deployment exception {{ alert.deployment.namespace }}/{{ alert.deployment.name }}
        description: Please investigate.  Deployment has been scaled to 0.
        issuetype: Task
      when: ticket_valid == false