- hosts: localhost
  connection: local
  tasks:
    - name: Echo vars
      vars: 
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }} 