- hosts: localhost
  connection: local
  tasks:
    - name: Check existence of ticket
      jira:
        uri: '{{ jira_uri }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        project: '{{ break_glass_annotation.split("-")[0] | upper }}'
        operation: fetch
        issue: '{{ break_glass_annotation }}'
      register: issue
    - name: Show issue
      debug:
        var: issue
    - name: Resolve Alert
      debug:
        msg: resolved!
      when: 
        - issue.issue.meta.fields.issueype.name == "Exception"
        - issue.issue.meta.status.name == "In Progress"

         